apiVersion: v1
kind: Service
metadata:
  name: nanobot
  namespace: nanobot
  labels:
    app: nanobot
spec:
  ports:
    - port: 18790
      targetPort: http
      name: http
  selector:
    app: nanobot
